language: node_js
cache: yarn
node_js:
  - "11"
  - "10"
script: yarn run test:cover:CI
before_install:
  - export TZ=Asia/Kolkata
after_success:
  # Send coverage data to coveralls.
  - yarn run test:cover:CI
