export const WEATHER_FETCH = 'WEATHER_FETCH';
export const WEATHER_FETCH_BEGIN = 'WEATHER_FETCH_BEGIN';
export const WEATHER_FETCH_SUCCESS = 'WEATHER_FETCH_SUCCESS';
export const WEATHER_FETCH_FAILURE = 'WEATHER_FETCH_FAILURE';

export const UI_SET_UNITS = 'UI_SET_UNITS';
export const UI_SET_DATE = 'UI_SET_DATE';
